// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Classification struct {
	ID        string     `json:"id"`
	ClassID   string     `json:"classId"`
	ClassName string     `json:"class_name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type CommonSuccessResponse struct {
	Message string `json:"message"`
}

type CreateClassification struct {
	ClassName string `json:"class_name"`
}

type CreatePerson struct {
	Name        string  `json:"name"`
	Address     *string `json:"address"`
	PhoneNumber *string `json:"phone_number"`
	ClassName   *string `json:"class_name"`
	Birthday    *string `json:"birthday"`
}

type GetPersonParams struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type Pager struct {
	Limit     *int    `json:"limit"`
	Offset    *int    `json:"offset"`
	ClassName *string `json:"class_name"`
}

type Person struct {
	ID          int        `json:"id"`
	PersonID    string     `json:"person_id"`
	Name        string     `json:"name"`
	Address     string     `json:"address"`
	PhoneNumber string     `json:"phone_number"`
	ClassName   string     `json:"class_name"`
	Birthday    *time.Time `json:"birthday"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}
